name: 'Spreadsheet to GitHub'
on:
  workflow_dispatch:
    inputs:
      spreadsheet_id:
        description: '1YtayIswh6oq2hQswTt-t_VS3P7O2QdQekuHZLguKaQQ'
        required: true

permissions:
  actions: write
  checks: write
  contents: write


jobs:
  push_data:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: スプレッドシートをCSVとしてダウンロード
        run: |
          wget -q -O data.csv "https://docs.google.com/spreadsheets/d/1YtayIswh6oq2hQswTt-t_VS3P7O2QdQekuHZLguKaQQ/export?format=csv"

      - name: データをコミット
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add data.csv
          git commit -m 'Update data from spreadsheet'
          git push